---

blacklist: config/mal_blacklist.txt
stats: config/tpch_sf100_stats.txt
query: 0


training_files: 
  - data/20180906-numa/trs/Q09.json
  - data/20180906-numa/trs/Q13.json
experiment: memory use per file
