---

root_path: /home/kutsurak/work/monet/sources/malcom
blacklist: config/mal_blacklist.txt
stats: config/tpch_sf100_stats.txt
query: 1
out_path: output/
data_file: /home/kutsurak/work/monet/sources/data/SF-100_traces/small/Q01_total.json.gz
