---

root_path: /home/kutsurak/work/monet/sources/malcom
blacklist: config/mal_blacklist.txt
stats: config/tpch_sf100_stats.txt
query: 1
outdir: output/
data_path: /home/kutsurak/work/monet/sources/data/SF-100_traces
