---

root_path: /home/kutsurak/work/monet/sources/malcom
blacklist: config/mal_blacklist.txt
stats: config/tpch_sf100_stats.txt
query: 1
out_path: output/
data_file: /home/kutsurak/work/monet/sources/data/SF-100_traces/full/Q01_total.json.gz

demo:
  training_set: /home/kutsurak/work/monet/sources/data/SF-100_traces/small/SF-100_small_training.json.gz
  model_storage: /home/kutsurak/work/monet/data/SF-100_traces/malcom_experiments/sf_100_small_model
  plan_file: /home/kutsurak/work/monet/sources/data/SF-100_traces/malcom_experiments/single_tests/Q06_variation100.json.gz
