---

blacklist: config/mal_blacklist.txt
stats: config/tpch_sf100_stats.txt
query: 1
out_path: output/
data_file: data/SF-100_traces/full/Q01_total.json.gz

demo:
  training_set: data/SF-100_traces/small/SF-100_small_training.json.gz
  # 'models' used to be: /home/kutsurak/work/monet/data
  model_storage: models/malcom_experiments/sf_100_small_model
