---

root_path: /home/kutsurak/work/monet/sources/malcom
blacklist: config/mal_blacklist.txt
stats: config/tpch_sf100_stats.txt
query: 0
out_path: output/
data_file: /home/kutsurak/work/monet/sources/data/SF-100_traces/small/SF-100_small_training.json.gz
model_file: /home/kutsurak/work/monet/sources/data/SF-100_traces/small/SF-100_small_training.model
