---

root_path: /Users/joeri/work/malcom/malcom
blacklist: config/mal_blacklist.txt
stats: config/tpch_sf100_stats.txt
query: 0
out_path: output/
data_file: /Users/joeri/work/malcom/data/SF100_traces/SF100_traces/Q13_total.json.gz
result_file: uhoh020.csv
experiment: actual memory
